name: Publish Docker image
on:
  workflow_run:
    workflows: ["Testing pipeline"]
    branches: [main]
    types: 
      - completed
jobs:
  Push_to_registry:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: discordbotsyksy/discordbot
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
